/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    CommentItem: typeof import('./components/CommentItem.vue')['default']
    CreatePostDialog: typeof import('./components/CreatePostDialog.vue')['default']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    EmotionVisualizer: typeof import('./components/EmotionVisualizer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
